name:  first

on:  push

jobs:
  job1:
    name:
    runs-on:
    steps:
    -  name:  Step one
       uses:  actions/checkout@v2
    -  name:  Step two
       run:  env | sort
  
  job2:
    name:
    runs-on:
    steps:
    -  name:  Step one
       uses:  actions/checkout@v2
    -  name:  Step two
       run:  "Get-ChildItem Env:  |  Sort-Object Name"
