name:  first

on:  push

jobs:
  job1:
    name:  First Job
    runs-on:  ubuntu-latest
    steps:
    -  name:  Step one
       uses:  actions/checkout@v2
       with:
         repository:  insightiq/ica2
         ref:  master
         path:  ./test_repo
    -  name:  Step two
       run:  |
            ls
            env | sort
    -  name: Python Syntax Checker
       uses: cclauss/Find-Python-syntax-errors-action@v0.2.0

